pipeline {
   agent any
    options {
      timeout(time: 1, unit: 'HOURS') 
    }
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Starting code checkout stage.'
                sh '''
                    #!/bin/sh
                    rm -rf
                '''
                git credentialsId: '17645', url: 'https://github.com/cmu-seai/movie-prediction-group-project-avengers.git'
                echo 'Code checked out successfully.'
            } // steps
        } // stage

        

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies'
                sh '''
                    #!/bin/sh
                    pip3 install -r ./CI/requirements.txt --user

                '''
            }  
        }

        stage('Evaluate Code Quality') {
            steps {
                script {
                    sh (
                        script: "python3 -m pytest --cov=./CI/ --cov-report=xml ./CI/pipeline_test/"
                    )
                }
                cobertura coberturaReportFile: 'coverage.xml'
                echo 'Code quality check completed.'
            } // steps
        } // stage
        



        stage('Build Model') {
            steps {
                script {
                    try {
                        sh (
                            script: 'python3 ./CI/pipeline.py',
                        )
                        plot csvFileName: 'plot_mean_precision.csv', csvSeries: [[file: 'plot_mean_precision.csv']], group: 'Measures', title: 'Offline Mean Precision', style: 'line', yaxis: 'Mean Precision'
                        plot csvFileName: 'plot_F.csv', csvSeries: [[file: 'plot_F.csv']], group: 'Measures', title: 'Offline Precision For Female', style: 'line', yaxis: 'Precision'
                        plot csvFileName: 'plot_M.csv', csvSeries: [[file: 'plot_M.csv']], group: 'Measures', title: 'Offline Precision For Male', style: 'line', yaxis: 'Precision'
                        plot csvFileName: 'plot_0-20.csv', csvSeries: [[file: 'plot_0-20.csv']], group: 'Measures', title: 'Offline Precision For Age 0-20', style: 'line', yaxis: 'Precision'
                        plot csvFileName: 'plot_21-35.csv', csvSeries: [[file: 'plot_21-35.csv']], group: 'Measures', title: 'Offline Precision For Age 21-35', style: 'line', yaxis: 'Precision'
                        plot csvFileName: 'plot_36-50.csv', csvSeries: [[file: 'plot_36-50.csv']], group: 'Measures', title: 'Offline Precision For Age 36-50', style: 'line', yaxis: 'Precision'
                        plot csvFileName: 'plot_51+.csv', csvSeries: [[file: 'plot_51+.csv']], group: 'Measures', title: 'Offline Precision For Age 51+', style: 'line', yaxis: 'Precision'
                    }
                    catch (Exception e) {
                        error ('There was an error while building the model.')
                    }
                }
            } // steps
        } // stage

        

        stage('Build & Deploy Prediction Service') {
             steps {
                sh 'JENKINS_NODE_COOKIE=dontKillMe nohup python3 ./CI/prediction_deploy.py > CI/server2.out &'
             } // steps
         } // stage

         stage('Evaluate API') {
            steps {
                script {
                    sh (
                        script: "python3 -m pytest --cov=./CI/ --cov-report=xml ./CI/test_recommendation_api.py"
                    )
                }
                echo 'API check completed.'
            } // steps
        } // stage

    } // stages
} // pipeline